### ISSUE TITLE
Have you created a 10.3 bundle reader?

### ISSUE THREAD

**Issue by peterb-2795** [FuZhenn/tiler-arcgis-compact#1]
Hi Fu zhen,

I have just come across your library.  Is this project still alive?  Have you done further work on it such that it can support the 10.3 bundle format?

Xie Xie ni,
zai jian
Peter

**Comment by fuzhenn** [comment]
Ni Hao, Peter,

Yes, this project is active.

Because arcgis tiles are rarely used in my projects now, I haven't digged into it.

And I don't have any 10.3 sample bundle data now, could you provide one for me? I am glad to find some time to complete this work.

**Comment by fuzhenn** [comment]
fixed in https://github.com/fuzhenn/tiler-arcgis-bundle/pull/2

Verifing in production.

**Comment by fuzhenn** [comment]
verified and published as 0.3.2
